config/routes.rb
Plusplus::Application.routes.draw do
  root :to => 'home#index'
  get "/humans.txt" => 'home#humanstxt', :format => :text, :as => :humanstxt
  get "/impressum" => 'home#impressum'
  get "/sponsoring" => 'home#sponsoring'
  get "/credits" => 'home#credits'
  get "/about" => 'home#about'
  get "/sponsors" => 'home#sponsors'
  get "/timetable" => 'home#timetable'
  
  get "/admin" => 'home#admin'
  
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index]
  resources :news, :only => [:index, :show]
  
  namespace :admin do
    resources :sponsors
    resources :users, :only => [:index, :edit, :update, :destroy] do
      member do
        get 'check_in'
        get 'check_out'
      end
      resources :tokens, :only => [:show, :destroy]
    end
    resources :news
  end
end

app/controllers/home_controller.rb
# coding: utf-8
class HomeController < ApplicationController
  def index
    @users = {
      :yes => User.yes,
      :waiting_list => User.waiting_list,
      :maybe => User.maybe
    }
    @sponsors = Sponsor.all
  end

  def impressum; end
  def sponsoring; end
  def credits; end
  def about; end
  def timetable; end

  def sponsors
    @sponsors = Sponsor.all
  end
  
  def humanstxt
    @humans = <<-_EOF_.split(/\n/).map(&:strip)
    wolfgang wopperer
    liron tocker
    friederike schmiedebach
    sven kräuter
    jan krutisch
    katrin kampfrath
    björn jensen
    fabian fabian
    matthias bauer
    _EOF_
  end
  
  def admin
    ensure_admin
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
#back= link_to "← back", root_path

.copy
  %h2 it's about all of us!
  %p When it comes to Agile, the case seems to be clear: It's on everyone's lips. Everyone has an idea what it's about. We all love the attitude. We all believe we practice – at least tiny bits – of it in our day-to-day work life. However, surprisingly few work teams thoroughly live and breathe agile. Especially when it comes to the areas of concept and design, the waterfall is dripping down our processes. 

  %h3 what is agile?
  %p The idea of introducing Agile Development often comes from the coders’ corner. It's then about convincing the rest of the team and, not to forget, the clients, since it turns the whole development process as they know it upside down: Agile requires everyone to rethink and reorganize his or her own participation up to the point where others are allowed and even required to enter one’s own sphere of competence. Agile is about the user and providing the user with the best possible product. No single person has all the answers, so it's about collaboration. Being confronted with intangible requirements sucks, so it's about user stories and prototypes to talk about. Real world data rocks, so it's about user testing from the beginning.
  %p All this has its consequences when adding design to the mix: Agile Design means coming out of the artist's cave and letting go of perfectionist dreams. Understanding design in terms of use, not in terms of visuals; as a collaborative process, not as a bold vision; as being required to stay rough, unfinished and open to feedback – all this challenges the designer's work.

  %h3 what does that mean?
  %p
    What are the skills required for working in an agile environment?
    %br
    What is left to do for the designer when everyone is allowed to talk about design concepts?
    %br
    At what point can I as a designer stand up for the aesthetic purpose?
    %br
    Is design now something that comes afterwards when the software is already there?
    %br
    How can visual and interface design inform and influence software development?
    %br
    How can design be developed in iterations and cycles, i.e. evolve?
    %br
    Will I have to code?

  %h3
    join us!
    %small= link_to 'register now', new_user_registration_path, :class => 'lightbox'
  %p These are some of the questions we’d love to discuss with you on the camp. Since Agile Development affects all team members, we want to invite not only visual designers, but also product and project managers, developers and UX experts. We believe this will give us the perspectives for a diverse and fruitful discussion. After all, Agile is more about collaboration than about processes and tools.

app/views/home/admin.html.erb
<h1>Admin</h1>
<h2><%= link_to 'Sponsors', '/admin/sponsors' %></h2>
<h2><%= link_to 'Participants', '/admin/users' %></h2>

app/views/home/humanstxt.text.erb
agile design camp {

               -oso:
          .dMNhooNMMm/
        ` ...sMMMMMMMM+
       hMMh+-sMMMMMMMMN`
    .-:NNhNMMMMMMMMMMMM-
    `/o/`  dMMMMMMMMMMM.
         -hMMNmdMMMMMMy
            `.-+NMMMMs
             -+syys+.

}


people in reverse alphabetical order:

<%= @humans.sort{ |a,b| b.split(/\s/)[-1] <=> a.split(/\s/)[-1] }.join("\n") %>


more credits:

- generic user icon from the Gnome Project under the GPL: http://www.iconfinder.com/browse/iconset/gnome-desktop-icons-png/

app/views/home/impressum.html.erb
<div class="privacy">
  <h2>Datenschutz</h2>
  <h3>Google Analytics</h3> 
  <p>Diese Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. („Google“). Google Analytics verwendet sog. „Cookies“, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website durch Sie ermöglichen.</p> 
  <p>Die durch den Cookie erzeugten Informationen über Ihre Benutzung dieser Website (einschließlich Ihrer <strong>anonymisierten</strong> IP-Adresse) wird an einen Server von Google in den USA übertragen und dort gespeichert. Google wird diese Informationen benutzen, um Ihre Nutzung der Website auszuwerten, um Reports über die Websiteaktivitäten für die Websitebetreiber zusammenzustellen und um weitere mit der Websitenutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. </p> 
  <p>Auch wird Google diese Informationen gegebenenfalls an Dritte übertragen, sofern dies gesetzlich vorgeschrieben oder soweit Dritte diese Daten im Auftrag von Google verarbeiten. Google wird in keinem Fall Ihre IP-Adresse mit anderen Daten von Google in Verbindung bringen. Sie können die Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser Software verhindern; wir weisen Sie jedoch darauf hin, dass Sie in diesem Fall gegebenenfalls nicht sämtliche Funktionen dieser Website vollumfänglich nutzen können.</p> 
  <p>Durch die Nutzung dieser Website erklären Sie sich mit der Bearbeitung der über Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>
</div>

<div class="imprint">
  <h2>Impressum</h2>
  <address>
    <span>Matthias Bauer</span>
    <br>
    Straßmannstraße 36
    <br>
    10249 Berlin
    <br>
    Germany
  </address>
  <ul>
    <li>
      e-mail:
      <a href="mailto:&#109;&#111;&#101;&#102;&#102;&#106;&#117;&#064;&#103;&#109;&#097;&#105;&#108;&#046;&#099;&#111;&#109;">moeffju&#064;gmail.com</a>
    </li>
    <li>
      phone:
      <a href="tel:+4917662372827">+49 (0)176 62372827</a>
    </li>
  </ul>
  <ul>
    <li>
      EU VAT ID:
      DE&nbsp;207&nbsp;49&nbsp;36&nbsp;21
    </li>
  </ul>
  <div id="imprint-notice">
    <small>Diese Daten dürfen nicht zu Werbezwecken genutzt werden.</small>
  </div>
</div>

app/views/home/index.html.haml
- content_for :javascripts do
  :javascript
    $(function(){
      $('#maybe').hide();
      $('#maybe h3 a').click(function(e){
        $('#maybe').hide();
        $('#yes').show();
        e.preventDefault();
        return false;
      });
      $('#yes h3 a').click(function(e){
        $('#yes').hide();
        $('#maybe').show();
        e.preventDefault();
        return false;
      });
    });
- content_for :header do
  %meta{property:"og:title", content:"agile design camp"}
  %meta{property:"og:type", content:"website"}
  %meta{property:"og:url", content:"http://www.agiledesigncamp.org/"}
  %meta{property:"og:image", content:"http://agiledesigncamp.org/images/facebook-image.png"}
  %meta{property:"og:site_name", content:"agile design camp"}
  %meta{property:"og:description", content:'Das agile design camp ist ein Barcamp zum Thema Agile Design. Agile Design dreht sich um die Integration der Arbeit von Designern in agile Softwareentwicklung, das Neudenken der Rolle von Design, und strukturiertes Denken.'}

#whatis
  %h2
    what is agile design?
    %small= link_to 'read on…', '/about'
  %p agile design is about integrating the designer's work into agile software development, rethinking the role of design and thinking in structures and pathways. agile design is user-driven, collaborative and open to change, and aims to deliver simple and rapid results. agile design is a new concept, not yet fully understood and seldom practised. this is why we have to talk about it.

#eventbox
  #eventdata
    agile design camp
    %br
    23./24. juli 2011
    %br
    = link_to 'betahaus hamburg', 'http://hamburg.betahaus.de/'
  - if current_user
    = link_to 'edit your profile', edit_user_registration_path
  - else
    = link_to 'register now', new_user_registration_path

- user_limit = 6
#participants
  %h2
    participants
    %small= link_to "show all #{@users[:yes].size}"+(@users[:waiting_list].present? ? " (+ #{@users[:waiting_list].size})" : ''), users_path, :title => "#{@users[:yes].size} attending, #{@users[:waiting_list].size} on waiting list"
  %ul.userlist
    - @users[:yes][0,user_limit].each do |user|
      %li.usertile= render :partial => 'shared/user', :locals => { :user => user }
    - if @users[:yes].size > user_limit
      %li= link_to "show all", users_path

#newsfeed
  %h2
    keynote
    - if false
      %small= link_to 'show all', news_index_path
  %p We are happy to announce Jeremy Tai Abbett (#{link_to '@jeremytai', 'https://twitter.com/jeremytai'}) as keynote speaker.
  %p Jeremy Tai Abbett is a teacher, hacker, strategist, interaction designer, and co-founder of Fork Unstable Media and Truth Dare Double Dare. Truth Dare Double Dare is a multi-disciplinary design firm with the goal of developing meaningful interactions through the intersection of art and technology.
  %p In his previous life, Jeremy was an award winning creative director, with three projects that were acquired by the Museum of Modern Art – San Francisco, a vert skater and a game that enraged the British Monarchy to his credit. He resides in Hamburg, Germany with his wife and two boys.

#sponsors
  %h2
    sponsors
    %small= link_to 'info for sponsors', sponsoring_path
  %ul
    - @sponsors.each do |sponsor|
      %li
        - unless sponsor.image_url.empty?
          = link_to image_tag(sponsor.image_url), sponsor.url, :alt => sponsor.name, :title => sponsor.name
        - else
          %big= link_to sponsor.name, sponsor.url, :title => sponsor.name

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/home/sponsoring.html.haml
.copy
  %h2 sponsoring
  %p If you are interested in supporting the agile design camp, please let us know. We will send you an information package with all the facts you need to know. Individual agreements are very welcome!
  %p contact us at <a href="mailto:&#111;&#114;&#103;&#097;&#064;&#097;&#103;&#105;&#108;&#101;&#100;&#101;&#115;&#105;&#103;&#110;&#099;&#097;&#109;&#112;&#046;&#111;&#114;&#103;">orga<b>&#064;</b>agiledesigncamp.org</a>

app/views/home/sponsors.html.haml
%h2 Sponsors

.items
  .item.sponsor-main
    %h3 XING – Das professionelle Netzwerk
    %p.i= link_to image_tag('http://moeffju.net/temp/adc11/xing.png', :alt => 'XING'), 'http://xing.com/'
    %p XING ist das soziale Netzwerk für berufliche Kontakte. Über 10,8 Millionen Mitglieder nutzen die Internet-Plattform weltweit für Geschäft, Job und Karriere, davon rund 4,7 Millionen im deutschsprachigen Raum. Auf XING vernetzen sich Berufstätige aller Branchen, suchen und finden Jobs, Mitarbeiter, Aufträge, Kooperationspartner, fachlichen Rat oder Geschäftsideen. Mitglieder tauschen sich online in über 45.000 Fachgruppen aus und treffen sich persönlich auf XING Events. Betreiber der Plattform ist die XING AG. Das Unternehmen wurde 2003 in Hamburg gegründet und ist seit 2006 börsennotiert. Im Dezember 2010 hat XING die in München ansässige amiando AG übernommen, Europas führenden Anbieter von Online-Eventmanagement und <span class="nbr">-Ticketing</span>. Weitere Informationen können unter #{link_to "www.xing.com", 'http://www.xing.com'} abgerufen werden.
  
  - [:gold, :silver].each do |level|
    %h4 #{level.to_s.capitalize} sponsors
    %div{class: "sponsors-#{level.to_s}"}
      - @sponsors.select{ |x| x.level == level }.each do |sponsor|
        .item{class: ['sponsor', sponsor.level]*'-'}
          %h3= sponsor.name
          - if sponsor.image_url
            %p= link_to image_tag(sponsor.image_url, :alt => sponsor.name), sponsor.url
          - else
            %p= link_to sponsor.url, sponsor.url

app/views/home/timetable.html.haml
%h2 Timetable

.col
  %h3 Saturday, July 23rd
  %table.timetable
    %tbody
      %tr
        %th 09:00
        %td Doors open
      %tr
        %th 09:00 – 11:30
        %td Breakfast
      %tr
        %th 10:00
        %td Sponsor intro: #{link_to 'XING', '/sponsors'}
      %tr
        %th 10:05
        %td
          Keynote: #{link_to 'Jeremy Tai Abbett', '/#newsfeed'}
          %br
          "Agile is to ______ as design is to programming."
      %tr
        %th 10:30
        %td Begin session planning
      %tr
        %th 11:30 – 13:00
        %td Sessions (45 minutes each: 30 min. session/15 min. break)
      %tr
        %th 13:00
        %td Lunch
      %tr
        %th 14:00 – 18:30
        %td Sessions (45 minutes each: 30 min. session/15 min. break)
      %tr
        %th 18:30
        %td
          Fireside chat:
          %br
          Björn Jensen, Jeremy Tai Abbett, N.N.
      %tr
        %th afterwards
        %td agile design camp party @ #{link_to "kopiba", 'http://kopiba.de/'}

.col.last
  %h3 Sunday, July 24th
  %table.timetable
    %tbody
      %tr
        %th 09:00
        %td Doors open
      %tr
        %th 09:00 – 11:30
        %td Breakfast
      %tr
        %th 10:00
        %td Sponsor intro: #{link_to 'mindmatters', 'http://mindmatters.de/'}
      %tr
        %th 10:05
        %td Begin session planning
      %tr
        %th 11:00 – 13:00
        %td Sessions (45 minutes each: 30 min. session/15 min. break)
      %tr
        %th 13:00
        %td Lunch
      %tr
        %th 14:00 – 16:00
        %td Sessions (45 minutes each: 30 min. session/15 min. break)
      %tr
        %th 16:00
        %td Wrap-up session
      %tr
        %th afterwards
        %td #{link_to "hacktable", 'http://hacktable.com/'}

%h3 Keynote: Jeremy Tai Abbett: "Agile is to ______ as design is to programming."
%p Jeremy Tai Abbett is a teacher, hacker, strategist, interaction designer, and co-founder of Fork Unstable Media and Truth Dare Double Dare. Truth Dare Double Dare is a multi-disciplinary design firm with the goal of developing meaningful interactions through the intersection of art and technology.
%p In his previous life, Jeremy was an award winning creative director, with three projects that were acquired by the Museum of Modern Art – San Francisco, a vert skater and a game that enraged the British Monarchy to his credit. He resides in Hamburg, Germany with his wife and two boys.

%h3 Fireside Chat: Björn Jensen, Jeremy Tai Abbett, Sebastian Deterding
%p tba