config/routes.rb
Plusplus::Application.routes.draw do
  root :to => 'home#index'
  get "/humans.txt" => 'home#humanstxt', :format => :text, :as => :humanstxt
  get "/impressum" => 'home#impressum'
  get "/sponsoring" => 'home#sponsoring'
  get "/credits" => 'home#credits'
  get "/about" => 'home#about'
  get "/sponsors" => 'home#sponsors'
  get "/timetable" => 'home#timetable'
  
  get "/admin" => 'home#admin'
  
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index]
  resources :news, :only => [:index, :show]
  
  namespace :admin do
    resources :sponsors
    resources :users, :only => [:index, :edit, :update, :destroy] do
      member do
        get 'check_in'
        get 'check_out'
      end
      resources :tokens, :only => [:show, :destroy]
    end
    resources :news
  end
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  default_scope :order => 'amount DESC, created_at ASC'
  
  def level
    case self.amount
    when 0..499; :supporter;
    when 500..799; :silver;
    when 800..1999; :gold;
    when 2000..1000000000; :main;
    end
  end
end

app/controllers/admin/sponsors_controller.rb
class Admin::SponsorsController < ApplicationController
  before_filter :ensure_admin
  
  # GET /sponsors
  # GET /sponsors.xml
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.xml
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.xml
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.xml
  def create
    @sponsor = Sponsor.new(params[:sponsor])
    logger.debug @sponsor.inspect
    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to(admin_sponsors_url, :notice => 'Sponsor was successfully created.') }
        format.xml  { render :xml => @sponsor, :status => :created, :location => @sponsor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sponsor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.xml
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to(admin_sponsors_url, :notice => 'Sponsor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sponsor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.xml
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to(admin_sponsors_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_filter :ensure_admin
  
  # GET /sponsors
  # GET /sponsors.xml
  def index
    @sponsors = Sponsor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sponsors }
    end
  end

  # GET /sponsors/1
  # GET /sponsors/1.xml
  def show
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sponsor }
    end
  end

  # GET /sponsors/new
  # GET /sponsors/new.xml
  def new
    @sponsor = Sponsor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sponsor }
    end
  end

  # GET /sponsors/1/edit
  def edit
    @sponsor = Sponsor.find(params[:id])
  end

  # POST /sponsors
  # POST /sponsors.xml
  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to(sponsors_url, :notice => 'Sponsor was successfully created.') }
        format.xml  { render :xml => @sponsor, :status => :created, :location => @sponsor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sponsor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sponsors/1
  # PUT /sponsors/1.xml
  def update
    @sponsor = Sponsor.find(params[:id])

    respond_to do |format|
      if @sponsor.update_attributes(params[:sponsor])
        format.html { redirect_to(sponsors_url, :notice => 'Sponsor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sponsor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.xml
  def destroy
    @sponsor = Sponsor.find(params[:id])
    @sponsor.destroy

    respond_to do |format|
      format.html { redirect_to(sponsors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/views/sponsors/_form.html.erb
<%= form_for @sponsor, :html => {:multipart => true} do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
      <% @sponsor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <% if @sponsor.image? %><%= image_tag(@sponsor.image_url) %> <%= f.check_box :remove_image %> Löschen?<br><% end %>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sponsors/index.html.erb
<h1>Listing sponsors</h1>

<p><%= link_to 'New Sponsor', new_sponsor_path %></p>

<table>
  <tr>
    <th>Name / URL</th>
    <th>Image</th>
    <th>Amount</th>
    <th></th>
  </tr>

<% @sponsors.each do |sponsor| %>
  <tr>
    <td><%= sponsor.name %><br><%= link_to sponsor.url, sponsor.url %></td>
    <td><% if sponsor.image.present? %><%= image_tag sponsor.image.url %><% else %>–<% end %></td>
    <td><big><%= sponsor.amount %>€</big></td>
    <td class="actions"><%= link_to 'Show', sponsor %> | <%= link_to 'Edit', edit_sponsor_path(sponsor) %> | <%= link_to 'Destroy', sponsor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/sponsors/new.html.erb
<h1>New sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sponsor.name %>
</p>

<p>
  <b>Image:</b>
  <%= @sponsor.image %>
</p>

<p>
  <b>Url:</b>
  <%= @sponsor.url %>
</p>


<%= link_to 'Edit', edit_sponsor_path(@sponsor) %> |
<%= link_to 'Back', sponsors_path %>