config/routes.rb
Plusplus::Application.routes.draw do
  root :to => 'home#index'
  get "/humans.txt" => 'home#humanstxt', :format => :text, :as => :humanstxt
  get "/impressum" => 'home#impressum'
  get "/sponsoring" => 'home#sponsoring'
  get "/credits" => 'home#credits'
  get "/about" => 'home#about'
  get "/sponsors" => 'home#sponsors'
  get "/timetable" => 'home#timetable'
  
  get "/admin" => 'home#admin'
  
  devise_for :users,:controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, :only => [:index]
  resources :news, :only => [:index, :show]
  
  namespace :admin do
    resources :sponsors
    resources :users, :only => [:index, :edit, :update, :destroy] do
      member do
        get 'check_in'
        get 'check_out'
      end
      resources :tokens, :only => [:show, :destroy]
    end
    resources :news
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= ((@title ? "#{@title} - " : '') + "agile design camp")
    = csrf_meta_tag
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = stylesheet_link_tag 'screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'ie.css', :media => 'screen, projection'
    = yield :stylesheets
    = javascript_include_tag 'jquery.min', 'rails', 'application', :cache => 'all'
    - if Rails.env.production?
      :javascript
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-24330973-1']);
        _gaq.push(['_trackPageview']);
        _gaq.push(['_trackPageLoadTime']);
        _gaq.push(['_gat._anonymizeIp']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    - else
      :javascript
        // Google Analytics is disabled in the development environment
        var _gaq = _gaq || [];
    = yield :javascripts
    = yield :header
  %body{:class => [params[:controller].split('/')[-1], params[:action]] * '-'}
    - if flash.present?
      #flash-holder
        #flash
          - flash.each do |key, msg|
            = content_tag :div, msg, :class => ["flash", key], :id => "flash_#{key}"
            :javascript
              setTimeout(function(){ $(window).bind('click mousemove keypress', function(){ $('#flash_#{key}').fadeOut('slow'); }) }, 1000);
    #userbar
      .w
        - if current_user
          .u
            .a
              - if current_user.image
                = image_tag(current_user.image, :alt => current_user.name)
            .nc
              = current_user.full_name
          - if is_admin?
            = link_to 'admin', admin_path
          = link_to 'edit profile', edit_user_registration_path
          = link_to "sign out", destroy_user_session_path
        - else
          = link_to "sign in", new_user_session_path, :class => 'lightbox'
    #wrapper
      #container
        %header#header
          %h1
            = link_to 'agile design camp', root_path
        %nav#nav
          %ul
            %li#l-homepage= link_to 'homepage', '/'
            %li#l-timetable= link_to 'timetable', '/timetable'
            %li#l-sponsors= link_to 'sponsors', '/sponsors'
            %li#l-users= link_to 'participants', '/users'
            %li#l-registration
              - if current_user
                = link_to 'edit profile', edit_user_registration_path
              - else
                = link_to 'sign up', new_user_registration_path
        #content
          = yield
    %footer#footer
      .w
        = link_to 'sponsoring', sponsoring_path
        = link_to 'credits', humanstxt_path
        = link_to 'privacy policy and imprint', impressum_path